PES-Sysplay/PES_WorkOut_APP

- app/src/main/java/com/example/workoutapp/ActivityController.java
> Search by activity name

- app/src/main/java/com/example/workoutapp/UserController.java
- app/src/main/java/com/example/workoutapp/ui/profile/ChangePasswordFragment.java
- app/src/main/java/com/example/workoutapp/ui/profile/ProfileFragment.java
- app/src/main/java/com/example/workoutapp/ui/usermanage/SharedPreferencesController.java
Implemented log out and change password is working
Fixes #
References #
> log out implemented

- app/src/main/java/com/example/workoutapp/Activitat.java
- app/src/main/java/com/example/workoutapp/ActivityController.java
- app/src/main/java/com/example/workoutapp/ui/home/ActivityDetail.java
- app/src/main/java/com/example/workoutapp/ui/home/HomeFragment.java
- app/src/main/res/layout/activity_scrolling.xml
- app/src/main/res/values/strings.xml
He implementat les funcionalitats seguents:
- Join Activity (#15)
- Leave Activity (#16)
> Join activity

- app/src/main/java/com/example/workoutapp/ActivityController.java
Wrong message showed when leaving an activity. Fixed!
> Correcció Missatge Volley a Leave Activity

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/workoutapp/ui/home/ReportActivity.java
- app/src/main/java/com/example/workoutapp/ui/home/ScrollingActivity.java
- app/src/main/res/drawable/ic_baseline_more_vert_24.xml
- app/src/main/res/layout/activity_report.xml
- app/src/main/res/layout/activity_scrolling.xml
- app/src/main/res/menu/scrolling_options_menu.xml
> Report activity

- app/src/main/java/com/example/workoutapp/ui/home/ActivityDetail.java
- app/src/main/res/layout/activity_scrolling.xml
> Fixed transition join activity

- app/src/main/java/com/example/workoutapp/Activitat.java
- app/src/main/java/com/example/workoutapp/ActivityController.java
- app/src/main/java/com/example/workoutapp/ui/calendar/CalendarFragment.java
- app/src/main/java/com/example/workoutapp/ui/home/ActivityDetail.java
- app/src/main/java/com/example/workoutapp/ui/home/HomeFragment.java
- app/src/main/java/com/example/workoutapp/ui/profile/SettingsActivity.java
- app/src/main/res/drawable/people_foreground.xml
- app/src/main/res/layout/content_scrolling.xml
> Number of participants and people joined finished

- .idea/misc.xml
- .idea/runConfigurations.xml
- app/src/main/java/com/example/workoutapp/UserController.java
- app/src/main/java/com/example/workoutapp/ui/profile/ChangePasswordFragment.java
- app/src/main/java/com/example/workoutapp/ui/profile/SettingsActivity.java
Arreglado bug para que solo se cambie de pantalla solo si se obtiene una respuesta correcta en los botones de cambiar contraseña y eliminar usuario.
Fixes #
References #
> Fixed bugs in change password and delete user

- .gitignore
adds new gitignore
Fixes #
References #
> gitignore this

- app/src/main/java/com/example/workoutapp/ui/home/ActivityDetail.java
- app/src/main/java/com/example/workoutapp/ui/home/QRActivity.java
- app/src/main/res/layout/activity_q_r.xml
- QR activity UX implemented
- Bug fixes
> QR UX implemented + bug fix

- .idea/misc.xml
- app/src/main/java/com/example/workoutapp/ui/calendar/CalendarFragment.java
- app/src/main/java/com/example/workoutapp/ui/home/ActivityDetail.java
- app/src/main/java/com/example/workoutapp/ui/home/ActivityListAdapter.java
- app/src/main/java/com/example/workoutapp/ui/userfeedback/ReviewFragment.java
Solved some bugs that appeared while merging 
Fixes #
References #
> solved merge bugs

- app/src/main/java/com/example/workoutapp/ui/profile/ProfileFragment.java
- app/src/main/java/com/example/workoutapp/ui/profile/SettingsActivity.java
En log out y delete user habia un bug al darle al boton de ir atrás de android y ha sido solventado. 
Fixes #
References #
> fixing bug in log out and delete user

- app/src/main/java/com/example/workoutapp/ui/myactivities/FutureTabFragment.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/OldTabFragment.java
There are no issues or new US. Just fixing bugs and deleting debug messages.
> Cleaning code 1

- app/src/main/java/com/example/workoutapp/ui/chat/ChatListActivity.java
- app/src/main/java/com/example/workoutapp/ui/home/ActivityDetail.java
- build.gradle
> Ivan fixes

- .idea/misc.xml
- app/src/main/java/com/example/workoutapp/ui/profile/ProfileFragment.java
- app/src/main/java/com/example/workoutapp/ui/profile/SettingsFragment.java
- app/src/main/res/drawable/border_bottom.xml
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/layout/profile_fragment.xml
change password button changed to settings
Fixes #
References #
> change password button changed to settings

- app/src/main/java/com/example/workoutapp/ui/calendar/CalendarFragment.java
- app/src/main/java/com/example/workoutapp/ui/home/HomeFragment.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/FutureTabFragment.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/MyActivitiesActivity.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/OldTabFragment.java
- app/src/main/java/com/example/workoutapp/ui/profile/FavoritesFragment.java
- app/src/main/java/com/example/workoutapp/ui/profile/ProfileFragment.java
- app/src/main/res/layout/activity_favorites.xml
- app/src/main/res/navigation/mobile_navigation.xml
He afegit fletxes cap endarrera i titols de action bar
Fixes #
References #
> fletxes endarrera i titols de actionbar

- app/src/main/java/com/example/workoutapp/ActivityController.java
- app/src/main/java/com/example/workoutapp/ui/favorites/ActivityFavorites.java
- app/src/main/java/com/example/workoutapp/ui/home/ActivityDetail.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/FutureTabFragment.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/MyActivitiesActivity.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/OldTabFragment.java
- app/src/main/java/com/example/workoutapp/ui/profile/FavoritesFragment.java
Fixes activity detail, and mis eventos, and mis favoritos
Fixes #
References #
> Activity detail

- .idea/misc.xml
- app/src/main/java/com/example/workoutapp/ui/chat/ChatListActivity.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/FutureTabFragment.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/OldTabFragment.java
- app/src/main/java/com/example/workoutapp/ui/profile/FavoritesFragment.java
Fix errors
Fixes #
References #
> api fix and error on mis eventos and mis favoritos

- .idea/compiler.xml
- .idea/misc.xml
- app/src/main/java/com/example/workoutapp/ui/chat/ChatActivity.java
- app/src/main/java/com/example/workoutapp/ui/chat/ChatListActivity.java
- build.gradle
> chat list fixed

- app/src/main/java/com/example/workoutapp/ui/home/ActivityDetail.java
- app/src/main/java/com/example/workoutapp/ui/home/QRActivity.java
- app/src/main/res/layout/activity_q_r.xml
- app/src/main/res/values/strings.xml
> Ivan fixes v35

- app/src/main/java/com/example/workoutapp/ui/home/ActivityDetail.java
- opt button fixed
Fixes #
References #
> options button fixed

- .idea/compiler.xml
- .idea/misc.xml
- app/src/main/java/com/example/workoutapp/ui/myactivities/MyActivitiesActivity.java
- app/src/main/java/com/example/workoutapp/ui/profile/FavoritesFragment.java
> fix nav navigation

- app/src/main/java/com/example/workoutapp/Activitat.java
- app/src/main/java/com/example/workoutapp/ui/home/HomeFragment.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/FutureTabFragment.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/OldTabFragment.java
- app/src/main/java/com/example/workoutapp/ui/profile/FavoritesFragment.java
> is old fixed

- app/src/main/java/com/example/workoutapp/LoginRegisterActivity.java
- app/src/main/java/com/example/workoutapp/UserSingleton.java
- app/src/main/java/com/example/workoutapp/ui/home/ActivityDetail.java
- app/src/main/java/com/example/workoutapp/ui/home/ActivityListAdapter.java
- app/src/main/java/com/example/workoutapp/ui/home/HomeFragment.java
> Bug share activity fix

- .idea/misc.xml
- app/src/main/java/com/example/workoutapp/UserActivityController.java
- app/src/main/java/com/example/workoutapp/UserSingleton.java
- app/src/main/java/com/example/workoutapp/ui/home/HomeFragment.java
- app/src/main/res/layout/fragment_settings.xml
- build.gradle
settings change appearance issue
Fixes #
References #
> settings change appearance issue

- .idea/misc.xml
- app/src/main/java/com/example/workoutapp/ActivityController.java
- app/src/main/java/com/example/workoutapp/UserActivityController.java
- app/src/main/java/com/example/workoutapp/UserController.java
- app/src/main/java/com/example/workoutapp/ui/home/ActivityDetail.java
- app/src/main/java/com/example/workoutapp/ui/home/ActivityListAdapter.java
- app/src/main/java/com/example/workoutapp/ui/home/HomeFragment.java
- app/src/main/java/com/example/workoutapp/ui/home/QRActivity.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/FutureActAdapter.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/FutureTabFragment.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/MyActivitiesActivity.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/MyActivitiesFragmentManager.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/OldActAdapter.java
- app/src/main/java/com/example/workoutapp/ui/myactivities/OldTabFragment.java
Made last refactoring, changed API URLs to master
Fixes #
References #
> Last PR before master

- app/src/main/java/com/example/workoutapp/UserController.java
fixed google bug
Fixes #
References #
> fix google bug on release

- app/src/main/java/com/example/workoutapp/ui/home/ActivityDetail.java
- Simplemente ahora funciona
Fixes #
References #
> last commit
